#!/usr/bin/env python

import sys
import torch
from diffusers import AutoencoderKL, ControlNetModel, EulerDiscreteScheduler
from diffusers import StableDiffusionControlNetPipeline

# append project directory to path so predict.py can be imported
sys.path.append('.')
from predict import BASE_MODEL, BASE_CACHE, CONTROL_CACHE, VAE_CACHE

vae = AutoencoderKL.from_pretrained(
    "stabilityai/sd-vae-ft-mse",
    torch_dtype=torch.float16,
    cache_dir=VAE_CACHE,
)
controlnet = ControlNetModel.from_pretrained(
    "monster-labs/control_v1p_sd15_qrcode_monster",
    torch_dtype=torch.float16,
    cache_dir=CONTROL_CACHE,
)
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    BASE_MODEL,
    controlnet=controlnet,
    vae=vae,
    safety_checker=None,
    torch_dtype=torch.float16,
    cache_dir=BASE_CACHE,
)
